version: '3.3'
services:
  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION}
    restart: always
    container_name: ${CONTAINER_NAMESPACE}-kafka-zookeeper
    hostname: kafka-zookeeper
    env_file: .env
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    volumes:
      - kafka-zookeeper-log:/var/lib/zookeeper/log
      - kafka-zookeeper-secrets:/etc/zookeeper/secrets
      - kafka-zookeeper-data:/var/lib/zookeeper/data
    networks:
      - network

  kafka-broker:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    restart: always
    container_name: ${CONTAINER_NAMESPACE}-kafka-broker
    hostname: kafka-broker
    env_file: .env
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=${CONTAINER_NAMESPACE}-kafka-zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_LOCAL_BROKER_HOSTNAME}:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - kafka-broker-data:/var/lib/kafka/data
      - kafka-broker-secrets:/etc/kafka/secrets
    networks:
      - network
    ports:
      - "9092:9092"

  telegraf:
    image: telegraf:${TELEGRAF_VERSION}
    container_name: ${CONTAINER_NAMESPACE}-telegraf
    hostname: telegraf
    environment:
      - KAFKA_LOCAL_TOPIC=${LOCAL_TOPIC}
      - KAFKA_BROKER=${CONTAINER_NAMESPACE}-kafka-broker:9092
      - KAFKA_CONSUMER_GROUP=${CONTAINER_NAMESPACE}-telegraf
      - INFLUXDB=http://${CONTAINER_NAMESPACE}-influxdb:8086
    volumes:
      - ./telegraf/telegraf-central.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - network

  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: ${CONTAINER_NAMESPACE}-influxdb
    hostname: influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - network

  grafana:
    image: grafana:${GRAFANA_VERSION}-plugins
    container_name: ${CONTAINER_NAMESPACE}-grafana
    hostname: grafana
    volumes:
      - ./grafana/grafana-central.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
    networks:
      - network
    ports:
      - "3000:3000"

  kafka-control-center:
    image: confluentinc/cp-enterprise-control-center:5.1.0
    container_name: ${CONTAINER_NAMESPACE}-kafka-control-center
    hostname: kafka-control-center
    env_file: .env
    environment:
      - CONTROL_CENTER_ZOOKEEPER_CONNECT=${CONTAINER_NAMESPACE}-kafka-zookeeper:2181
      - CONTROL_CENTER_BOOTSTRAP_SERVERS=${CONTAINER_NAMESPACE}-kafka-broker:9092
      - CONTROL_CENTER_REPLICATION_FACTOR=1
      - CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1
      - CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1
      - CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS=2
      - CONTROL_CENTER_CONNECT_CLUSTER=http://kafka-connect:8082
    ulimits:
      nproc: 65535
      nofile:
        soft: 16384
        hard: 16384
    networks:
      - network
    ports: 
      - "9021:9021"

volumes:
  kafka-zookeeper-log:
  kafka-zookeeper-secrets:
  kafka-zookeeper-data:
  kafka-broker-data:
  kafka-broker-secrets:
  influxdb-data:
  grafana-data:

networks:
  network:
